predefined_responses = {
    
            "hello": "Hi! How can I help you today?",
            "hi": "Hello! What can I do for you?",
            "how are you?": "I'm just a bot, but I'm doing well. Thanks for asking!",
            "bye": "Goodbye! Have a great day!",
            "what is programming?": "Programming is the process of creating instructions for a computer to execute. It involves writing code in a programming language to solve problems or perform tasks.",
            "what is python?": "Python is a high-level, interpreted programming language known for its simplicity and readability.",
            "what is a class in python?": "A class in Python is a blueprint for creating objects. It defines attributes and methods that the objects created from the class will have.",
            "what is a function?": "A function is a block of reusable code that performs a specific task. It can take inputs, process them, and return an output.",
            "what is a variable?": "A variable is a container for storing data values. In Python, you don't need to declare the type of a variable explicitly.",
            "what is an if statement?": "An if statement is used for decision-making in Python. It allows you to execute a block of code only if a specified condition is true.",
            "what is a loop?": "A loop is used to iterate over a sequence (like a list, tuple, or string) or execute a block of code repeatedly while a condition is true.",
            "what is inheritance?": "Inheritance is a feature in object-oriented programming that allows a class to inherit attributes and methods from another class.",
            "what is polymorphism?": "Polymorphism allows objects of different classes to be treated as objects of a common superclass. It is often achieved through method overriding.",
            "what is encapsulation?": "Encapsulation is the practice of bundling data and methods that operate on that data within a single unit, like a class, and restricting access to some of the object's components.",
            "what is a decorator in python?": "A decorator is a function that modifies the behavior of another function or method. It is often used to add functionality to existing code.",
            "what is a lambda function?": "A lambda function is an anonymous function in Python, defined using the `lambda` keyword. It can have any number of arguments but only one expression.",
            "what is the difference between a list and a tuple?": "A list is mutable, meaning it can be modified after creation, while a tuple is immutable and cannot be changed after creation.",
            "what is a dictionary in python?": "A dictionary is a collection of key-value pairs in Python. It is unordered, mutable, and indexed by keys.",
            "what is an algorithm?": "An algorithm is a step-by-step procedure or formula for solving a problem or performing a task.",
            "what is a data structure?": "A data structure is a way of organizing and storing data so that it can be accessed and modified efficiently.",
            "what is an array?": "An array is a collection of items stored at contiguous memory locations. It is used to store multiple values of the same type.",
            "what is recursion?": "Recursion is a programming technique where a function calls itself to solve smaller instances of a problem.",
            "what is a module in python?": "A module in Python is a file containing Python code, such as functions and classes, that can be imported and reused in other programs.",
            "what is an exception?": "An exception is an error that occurs during the execution of a program. Python provides a way to handle exceptions using try-except blocks.",
            "what is a file in python?": "A file in Python is used to store data. You can open, read, write, and close files using Python's built-in file handling functions.",
            "what is a package in python?": "A package in Python is a collection of modules organized in directories that provide a way to structure and reuse code."
}